FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR '/docker/dotnet-sdk'

RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt update && apt install -y apt-transport-https dotnet-sdk-2.1 dotnet-runtime-2.1
RUN dotnet tool install --global dotnet-ef